### PR TITLE
HNG FAQ page 1

### PR DESCRIPTION
**Pull request by EbereUzodufa**
We create the page and made it mobile responsive.
We used faq.json in data for making FAQ dynamic. We can always add there to increase the number of the FAQ.

Test URL => https://hng6.netlify.com/faq.html

### CODE REVIEW

**Comment by KingAbesh** [comment]
Great job guys.

**Comment by KingAbesh** [comment]
I have a problem with how your footer renders on mobile. were you also assigned the footer task or did you just include it to give your page semantic meaning ?

**Comment by EbereUzodufa** [comment]
We were not assigned that but had to make it responsive.

What was the issue?

**Comment by EbereUzodufa** [comment]
Oh Okay.
Just playing with even and odd nth-child(). Saw the design on Dribble or so.

I agree with you. The center is better.

**Pull request merged**
