### PR TITLE
Donation payment with flutterwave gateway and a little animation in the mentors page

### PR DESCRIPTION
**Pull request by Jaysalasi**
couldn't make all the images animate but i did what i could do

### CODE REVIEW

**Comment by phiiileo** [comment]
Test link

**Comment by Jaysalasi** [comment]
https://jaysalasi.github.io/HNG6.0/quickdonation.html

https://jaysalasi.github.io/HNG6.0/mentorpage.html

**Comment by phiiileo** [comment]
Send me message on slack, I don't undertsand what you did on mentor page, and also pay with flutter stuff...comman explain

**Comment by Jaysalasi** [comment]
whats your slack name?

**Pull request merged**
