### PR TITLE
contactform and file layout

### PR DESCRIPTION
**Pull request by Ayenko4all**

### CODE REVIEW

**Comment by phiiileo** [comment]
Test link

**Comment by Ayenko4all** [comment]
What test link?

**Comment by phiiileo** [comment]
Host the page you worked on so i can test it

**Comment by Ayenko4all** [comment]
That code i push is working but won't submit to database the other need to
complete that past i internationally remove that part from it so he can
work on it any thing that will be need to be shipped in will come
later...just merge and let him clone and work.......i even do a layout for
others to follow so that the work can be clean

**Comment by Ayenko4all** [comment]
000webhostapp.com/HNG6.0/contactform.php

**Comment by Ayenko4all** [comment]
https://jocund-techniques.000webhostapp.com/HNG6.0/contactform.php

**Pull request merged**
