### PR TITLE
Mentors page

### PR DESCRIPTION
**Pull request by 6lack6ix**
Screenshot_2019-10-10-16-03-41-1367718604
Screenshot_2019-10-10-16-04-08-1009876062

Took screenshots with my phone because my system is low

### CODE REVIEW

**Comment by Ezeko** [comment]
please host the site

**Comment by 6lack6ix** [comment]
These is the URL to the site => https://admiring-leavitt-8d2ec2.netlify.com/mentorspage

**Comment by Ezeko** [comment]
Screenshot_20191010-185153

Page not properly responsive. Please rectify.

**Comment by 6lack6ix** [comment]
I have rectify the page => https://hardcore-jones-2b7f5d.netlify.com/mentorspage.html

**Comment by Ezeko** [comment]
A little more work on the hamburger menu and also fix the extra whitespace after the footer.

**Comment by phiiileo** [comment]
I will close this PR, send another when you have made those corrections

**Pull request closed without merging**
