### PR TITLE
Redesign of footer.html

### PR DESCRIPTION
**Pull request by AgbenigaAgboola**
http://hngi6.wpgroom.com/footer.html

### CODE REVIEW

**Comment by phiiileo** [comment]
What exactly did you do?

**Comment by AgbenigaAgboola** [comment]
I redesign the footer.html from this image below to this ===>http://hngi6.wpgroom.com/footer.html
screencapture-127-0-0-1-59880-footer-html-2019-10-15-21_42_33

**Comment by AgbenigaAgboola** [comment]
> What exactly did you do?

@phiiileo #139 
I redesign the footer.html from this image below to this ===>http://hngi6.wpgroom.com/footer.html
screencapture-127-0-0-1-59880-footer-html-2019-10-15-21_42_33

**Comment by phiiileo** [comment]
You are to work on the individual footer on the page ...This particular page is not used in any of the pages

**Pull request closed without merging**
