### PR TITLE
Fixed accordion and excess margins

### PR DESCRIPTION
**Pull request by faruq2**
Test url: https://faruq2.github.io/HNG6.0/

Accordion now works!

### CODE REVIEW

**Comment by phiiileo** [comment]
On which of the pages???

**Comment by faruq2** [comment]
@phiiileo index.html

**Comment by phiiileo** [comment]
There's no accordion on index.html

**Comment by faruq2** [comment]
@phiiileo There is
Screenshot_20191013-144632_Chrome

**Pull request merged**
