### PR TITLE
Added responsiveness

### PR DESCRIPTION
**Pull request by emmypuch**

### CODE REVIEW

**Comment by KingAbesh** [comment]
please provide a hosted link showing this in action. You can use github pages

**Comment by emmypuch** [comment]
https://emmypuch.github.io/HNG6.0/.

**Comment by KingAbesh** [comment]
hmm only your readme is rendering. can you attach screenshots for desktop and mobile view ?

**Comment by KingAbesh** [comment]
wrong repo. please make a PR to the lancers repo

**Pull request closed without merging**
