### PR TITLE
Added footer.html - a reusable footer for hng site

### PR DESCRIPTION
**Pull request by oluscc**
# To make use of the footer section: 
        #1. Make sure the 2 <link> and 2 <script> declared in the <head> of this html file (or their equivalent) are declared in your page's <head>
        #2. Add the commented out <script> in the <head> of this html file to your page's <head> 
        #3. Set an id="footer" attribute for the <div> or <section> where you want your footer to appear in your page
hng-footer

### CODE REVIEW

**Comment by KingAbesh** [comment]
Did you work on this alone ?

**Comment by KingAbesh** [comment]
also provide a hosted link to show how it renders on mobile.

**Comment by oluscc** [comment]
No I didn't work on it alone. Three of us did. Namely, @Dev_Phileo, @Oluscc and @Hayjay .

**Comment by oluscc** [comment]
It is hosted and tested here https://oluscc.github.io/hng6footer/

I will get the mobile screenshots across shortly.

**Comment by oluscc** [comment]
@Dev_phileo is a Slack user name. Here is the GitHub name: @phiiileo

**Comment by Ezeko** [comment]
Merged

**Pull request merged**
