### PR TITLE
Refined the HNG home page

### PR DESCRIPTION
**Pull request by faruq2**
I removed the excess padding and fixed broken links.
I also had to properly insert a bug fix(sponsor and support) from a previous merge.

### CODE REVIEW

**Comment by phiiileo** [comment]
Drop url test please

**Comment by faruq2** [comment]
Test url: 
https://faruq2.github.io/HNG6.0/index.html

**Comment by phiiileo** [comment]
The footer is not mobile friendly

**Comment by faruq2** [comment]
@phiiileo 
I didn't say I was going to work on the footer
I used what was there before
Someone should write the code for a reusable footer

**Pull request closed without merging**
