### PR TITLE
8 pages updated now have consistent footer

### PR DESCRIPTION
**Pull request by oluscc**
index.html is not responsive.

### CODE REVIEW

**Comment by oluscc** [comment]
footer of mentorpage.html is still not consistent with all other footers even though it is responsive.

The author(s) of the page may have to check the codes to fix the bug.

**Comment by fabianuzukwu** [comment]
include testing link please

**Comment by phiiileo** [comment]
Thanks

**Comment by oluscc** [comment]
You closed the PR without merging?

Testing links? I don't understand.

**Pull request closed without merging**
