### PR TITLE
Worked on the faq pag

### PR DESCRIPTION
**Pull request by olaleye247**
I added the necessary changes like the collapsible faq and the nav links.

### CODE REVIEW

**Comment by phiiileo** [comment]
Url for testing

**Comment by Ezeko** [comment]
Kindly host the page and submit url for testing!

**Comment by olaleye247** [comment]
https://peaceful-lamport-54fb41.netlify.com/ you can test the faq page here. I have made some changes since i uploaded this link like hosting images on cloudinary

**Comment by Ezeko** [comment]
The image is not displaying.. kindly host the image online and add the link to your design. Also, do not push to master. Create a branch locally to push your work before creating PR. Lastly, try to use hamburger for the mobile menu... You can check other repositories for inspiration. Thanks

**Pull request closed without merging**
