### PR TITLE
Added the readme file and the html file for the join inter page 

### PR DESCRIPTION
**Pull request by iwa-temmy**
Screenshot_2019-10-10 Join as an intern

### CODE REVIEW

**Comment by KingAbesh** [comment]
hosted link please

**Comment by iwa-temmy** [comment]
> hosted link please

https://iwa-temmy.github.io/HNG-internship-Frame-3.2/

**Comment by KingAbesh** [comment]
and please make the submit button bigger

**Comment by KingAbesh** [comment]
good job. comment your teammate names and yours too. will merge soon

**Comment by iwa-temmy** [comment]
@miz-kas @UwemEsther @Dennis.O @Akolawole @Dekiller_j -Team Lead

**Comment by KingAbesh** [comment]
that’s okay. love you’re navbar

**Pull request merged**
