### PR TITLE
Fixed how it works bug

### PR DESCRIPTION
**Pull request by Joshuafolorunsho**
image
One of the two images disappears when on mobile. It is fixed now

check -> 
image

fixed the calendar also -> 
Before 
image

After 
image

If you want me to make some changes. Please drop a comment. Thanks!

### CODE REVIEW

**Comment by Joshuafolorunsho** [comment]
Test url here => https://joshuafolorunsho.github.io/HNG6.0/

**Comment by fabianuzukwu** [comment]
Please i don't understand what you fixed on calender

**Comment by Joshuafolorunsho** [comment]
I'll make changes

**Comment by Joshuafolorunsho** [comment]
Can you explain why you closed the Pr Phiiileo?

**Comment by phiiileo** [comment]
Check
Screenshot_20191013-115457
You have one of your reason

**Comment by Joshuafolorunsho** [comment]
image
This is an existing bug @phiiileo . I didn't touch the nav bars

see proof up there

**Pull request closed without merging**
